### ISSUE TITLE
nit: mock client non-error return value check

### ISSUE THREAD

**Issue by bennetyee** [oasislabs/developer-gateway#157]
https://github.com/oasislabs/developer-gateway/blob/8b139f2d71e177d63cceab863291bc0d934f148a/api/v0/event/handler_test.go#L139

instead of `_` for the id part of the returned tuple, maybe capture it and assert that it is `nil`?  i don't think we'd ever want to deviate from the go idiom / pattern that if the `err` part of the tuple is non-nil that the normal result part is valid.

**Comment by eauge** [comment]
fixed by https://github.com/oasislabs/developer-gateway/pull/175
