### ISSUE TITLE
nit: No explicit API versioning in the API

### ISSUE THREAD

**Issue by bennetyee** [oasislabs/developer-gateway#158]
The API `api/v0/...` has no call for the client to request the API version number (0).

## Details

While the absence of something like an `ApiVersionRequest` suffices for a client to determine that the server is a v0 server, it is probably a good idea to add such a request earlier rather than later.  The exposed requests as well as request parameters may change, and we would want a v1 (or higher) client to be able to determine if it is talking to a server that only supports an older API, especially if the semantics of a request (and not necessarily its parameters) changes.  Hopefully exposing a server that supports older APIs would only happen due to extremely rare misconfigurations. Having clients detect when they are v0 software when the server is running a v1 or higher API, however, may be more important, since we may not be able to control if/when users will know to update their clients.  Having an `ApiVersionRequest` allows clients to issue a warning or refuse to run when they detect that they are not up-to-date.

This is related to #153 

## Acceptance Criteria
Some way clients can determine server API version exists.

**Comment by eauge** [comment]
fixed by https://github.com/oasislabs/developer-gateway/pull/175
