### ISSUE TITLE
Developer-gateway needs to get the API Token from the request and use it with the dashboard to verify the request.

### ISSUE THREAD

**Issue by nhynes** [oasislabs/developer-gateway#186]
@eauge commented on [Thu Aug 15 2019](https://github.com/oasislabs/oasis-cli/issues/102)

---

@nhynes commented on [Thu Aug 15 2019](https://github.com/oasislabs/oasis-cli/issues/102#issuecomment-521750930)

Issue moved to [oasislabs/developer-gateway #185](https://github.com/oasislabs/developer-gateway/issues/185) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sharmaster96** [comment]
Seems to be a replica of #185
