### ISSUE TITLE
Nonce tracking gets into a corrupt state

### ISSUE THREAD

**Issue by armaniferrante** [oasislabs/developer-gateway#22]
The developer gateway easily loses track of its nonce. E.g. 

```
{"address":"0x372FF3aeA1fc69B9C440A5fE0B4c23c38226Da68","call_type":"ExecuteTransactionFailure","class":"EthClient","err":"Transaction execution error with cause: Invalid transaction nonce: expected 789, found 803","id":4,"level":"debug","msg":"failure to send transaction","pkg":"eth","time":"2019-05-14T22:09:20-07:00","traceId":-1}
```
Filing to track the issue. Will spend time for exact repro steps if needed. Let me know @eauge.

We can fix this by calling the eth_getTransactionCount web3 rpc (or whatever the equivalent ekiden request is).

**Comment by eauge** [comment]
I'll close this because since May we completely changed how the nonces are managed, so this shouldn't be a problem. If it still happens, we should open another ticket
