### ISSUE TITLE
subscription takeover

### ISSUE THREAD

**Issue by eauge** [oasislabs/developer-gateway#75]
When a client subscribes to the developer-gateway, a specific instance of the developer-gateway creates a subscription and pushes all the events to a mailbox. If this instance of the developer-gateway crashes, and another instance of the developer-gateway gets a request to poll for subscription events, the developer-gateway instance can be the one taking over the subscription.

This would only work when using the redis provider, we cannot do this with the mem provider.

**Comment by armaniferrante** [comment]
Aug 20 Devex meeting. Closing in favor of https://github.com/oasislabs/oasis.js/issues/234.
